version: '3.6'
services:
  pytorch-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8877:8888
    volumes:
      - ./mydata:/home/jovyan/work:rw
      #  - C:\Users\p10258338\Documents\python\pytorch\mydata:/home/jovyan/work:rw
    command: start-notebook.sh --NotebookApp.token=''
    restart: always
  
# docker-compose.exe up
# winpty docker-compose.exe exec pytorch-notebook bash
# docker-compose.exe stop; docker-compose rm; docker-compose up